runtest: \
test/test.c \
test/test-game.c \
test/test-possible-move-generators.c \
$(wildcard test/generator-tests/*.c) \
game.c \
possible-move-generators.c

	gcc -o bin/runtest \
	test/test.c \
	test/test-game.c \
	test/test-possible-move-generators.c \
	$(wildcard test/generator-tests/*.c) \
	game.c \
	possible-move-generators.c